groups:
  - name: contact-book-alerts
    rules:
      - alert: PageAccess3Times
        expr: changes(http_requests_duration_seconds_count[5m]) >= 3
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "Page was accessed more than 3 times in 5 minutes"
          description: "The page has been accessed more than 3 times in the last 5 minutes"